### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO29_My_Summer_Tanks.ruha#1]
1. [x] Слоты с непонятными названиями, но без пояснений. Добавить описание слотов на экран сеттингов (см. https://github.com/rempopo/CO20_Operation_Pink_Citadel.abramia/blob/f53980208e82d7cbef741c2c6220b5854d95f910/description.ext#L17)

2. [x] Нарушен порядок отрядов на слотинге. Удалить отряды, поставить заново в правильном порядке

3. [x] Названия групп не указаны. См. https://github.com/CBATeam/CBA_A3/wiki/Name-Groups-in-Lobby  Нужно будет только в GAT правильные имена ролей вписать

4. [x] Section Commander вместо привычного Section Leader. Возможно стоит заменить, чтобы не смущать умы

5. [x] Скриптовая ошибка при запуске:
```11:19:39 Error in expression <Condition1 = [ "WIN", "[ [TGT1, TGT2], "east", "primaryWeapon _x != ''", "< 3"] >
11:19:39   Error position: <east", "primaryWeapon _x != ''", "< 3"] >
11:19:39   Error Missing ]
11:19:39 File C:\Users\XXXX\Documents\Arma 3 - Other Profiles\10Dozen\mpmissions\CO29_My_Summer_Tanks.ruha\dzn_tSFramework\Modules\MissionConditions\Settings.sqf..., line 51
```

Зачем использован код строкой если не умеешь им пользоваться?

6. [x] Автор миссии не указан. Давайте указывать, а то потом хз кто что никто не помнит. В любом случае `TS` - невалидное значение. 

7. [x] Обозначение MSR WAY в нижней части карты не читабельно

8. Брифинг: "Враждебные силы" -- советы и рекомендации перенести в п.п. Выполнение, враждебные силы свести в список

9. Брифинг: "Враждебные силы" -- "около 4 танками" заменить на "примерно 4 танками"

10. Брифинг: "Враждебные силы" -- "через 60 минут после начала". Начала чего? 

11. Брифинг: "Враждебные силы" -- второй абзац разделить на несколько логических частей (про QRF, про ПТО, про развед патрули), не очень понятно что должно значить -  "вражеская рота продолжит занимать об. позиции" 

12.  [x] Брифинг: "Дружественные силы" -- в брифинге Steelrain, а на карте Steel Rain. "Второй взвод" выглядит как просто числительное (там первый, тут второй), лучше делать также как на карте - 2ой взвод

13. Брифинг: "Поддержка" -- количество техники обозначить через 1х, 5х и т.п.

14. Брифинг: "Поддержка" -- побольше ландроверов, все таки хрупкие, а могут пригодиться

15. Брифинг: "Замечания" -- Информация про редеплой наверное излишняя, это стратегия игры которая требует обкатки и возможно мы от нее откажемся. Лучше перенести в замечания для ГСО.

16. Брифинг: "Поддержка" --  Про КВ рации указать первым пунктом.

17. Брифинг: "Замечания для ГСО" -- зачем создавать ГСО (и ебацца с выдачей нужны штук), если можно скрептами? Пиши в личку если хочешь узнать как

18. Брифинг: "Замечания для ГСО" -- про минометы странное правило. Обсудить!

19. [x] Эквип: Раций нет, зато QuikClot есть =\

20. [x] Эквип: Зачем Секшен лидеру лента?

21. [x] Не очень понятно - зачем давать область размещения ЦЦП/ФАРП, но при этом область имеет ровно 1 вариант для выбора - в поле, вплотную к LD?  Просто в Kantola размести, да и все, псевдовыбор нинужин.

22. [x] dzn_Gear включен, нужно выключить

23. [x] Эквип: Платун Командеру выдан огроменный рюкзак, лучше ST-138 AN/PRC-77

24. [x] Эквип: Возможно в танке не нужно хрнаить 6 МААВСов, 30 гранат и т.п. Просто медкитка и патроны для оружия экипажей, десяток дымовых, пару "лишних" лент для пулемета (типа для танкового, но можно поделиться с пехотой)

25. [x] Артиллерия: Добавить больше ILLUM миссий, т.к. у нас древние века и ночью будет пиздец без света

26. [x]  Эквип: По 4 магазина на рыло у ФТЛ/СЛ? Малавата буит, добавить еще 2-3 трассерных

27. [x]  Эквип: Броники у когото есть (экипаж, мг), а у когото нет (остальные). Это намеренно?

28. [x] По воронкам на технике чото не проехать (танк застревает, хз мож в брифинге язвительно заметить что танкостроители британии сделали автострадный танк). После доп тестов понял что танк застревает вообще везде, нужно костыль скриптовый писать чтобы доп скорость давать =(

29. [x] Хм... у меня чото БМП-2 танк не атаковала. Потести и замени на РХСную если не атакует

30. [x] FV432 из БМП-2 не шьется вообще (едва только пулемет отбили в два ствола), РХСная аналогично, но та хоть ПТУР пустила с 50% демеджа

31. [x] С учетом хуевости танков - лучше MSR сделать чуть менее загруженной объектами - растащи их по сторонам от дороги, а то заебемся танки возить (потому шо съехав с дороги они могут на нее и не вернуться вовсе)

32. [x]  Патрули рандомные ползают по полям, лучше натыкать маленьких зон по лесам, чтобы их просто так не видно было, а в случае чего они сами или гсо их из лесу мог вытащить.

33. [x]  У танка по правому флангу надо маленько пехоты (3-4) насыпать в лесочке, чтобы если фланковать то его ктото прикрыл бы

34. [-] На левом фланге может поставь две БРДМки патрулировать (road patrol) и к ней пехотку (3 рыла), плюс две фаертимы ползают вдоль леса с севера на юг. Тогда у ГСО будет возможность пихоту которая фланговать (если пойдет) и из БРДМ одобрить

35. [x] Пихота в лесу за Obj Hammer не очень понятно зачем. Лучше их в Hietalanmaki разместить, чтобы ГСО мог потом их мог на подкреп кинуть или к город, или на Obj Hammer. Тем более там БМП-2 в лес заезжает и застревает нахуй, пусть лучше стоит в городе спрятнная как резерв.

36. [x] Танчик около Ohmenluoma (справа) коллайдится об укрытие и крю вылазит, починити

37. [-] Выглядит миссия очень длинной, нужно предусмотреть возможность передвигать CCP и FARP (в Заметках для ГСО и в выполнении, правда при переносе фарп ломается сервис машин, но хотя бы номинально перенести, а потом уже хоть чем лечить-чинить), иначе поездки на реарм и хил будут занимать две вечности; либо добавить вертолет какойнить для эвакуаций, а то и авиаудар какой

38. [x] В редакторе в сеттингах (там где дата и время выбираются) выбрать Performance и отключить все чекбоксы шо увидишь

39. [x] Интро Текст добавить!

40. [x] FARP поменять на чтото больше похожее на способное перезарядить танк

41. [x] Стоят 105мм гаубицы, но не доступны нигде. Пусть хоть через ГСО будут доступны.

42. Подвинуть вертолет и его иконку на вертолетную площадку

43. FARP позволяет взять ПНВ. Чтобы запретить - поменять тут https://github.com/rempopo/CO29_My_Summer_Tanks.ruha/blob/a2c05502090bea426fe9beaadf6c5888bd4b5af3/dzn_tSFramework/Modules/FARP/Settings.sqf#L30 на false

44. У ФТЛа usm_pack_st138_prc77, хотя у него КВха. Получается и КВ и ДВ одновременно =\

**Comment by OneScheer** [comment]
> 20. :question: Эквип: Зачем Секшен лидеру лента? 

Согласно лоадауту отделения пехоты армии Великобритании на 70-е года. (https://www.battleorder.org/uk-rifle-co-1976)

> 26. Эквип: По 4 магазина на рыло у ФТЛ/СЛ? Малавата буит, добавить еще 2-3 трассерных
4 магазина (80 патронов) вполне достаточно для выполнения своих задачи командирам. 

Добавлю ещё 2 трассерных магазина.

> 27. Эквип: Броники у когото есть (экипаж, мг), а у когото нет (остальные). Это намеренно?

Да, намеренно. Flak Vests не были широко распространены.

> По воронкам на технике чото не проехать (танк застревает, хз мож в брифинге язвительно заметить что танкостроители британии сделали автострадный танк). После доп тестов понял что танк застревает вообще везде, нужно костыль скриптовый писать чтобы доп скорость давать =(

Если всё плохо, попробую заменить танк ворриором

Насчёт БМП-2 и FV432 не знаю что делать. Заменить APC лэндроверами?

Потестил танки, пиздец. Застревает на любой кочке.

**Comment by 10Dozen** [comment]
Вот тут скрипт позволяющий добавить мощности машине: https://github.com/10Dozen/ArmaDesk/blob/master/ScriptLand/VehicleLowGear.sqf

В мисску можешь вставить внутрь файла initPlayerLocal.sqf (он у тебя не используется, так шо просто создай его и вставь туда скрипт).  Укажи класснейм танков в массиве dzn_lowGear_compatibleVehicles (там уже стоит челенджер, но не уверен что тот который ты юзаешь).

В брифинге в заметках укажи, что у танков чтобы воспользоваться пониженной передачей нужно `Вперед + Левый Shift`, для движения назад - `Назад + Правый Shift`

**Comment by OneScheer** [comment]
Добавил скрипт и добавил описание в брифинг.

**Comment by 10Dozen** [comment]
Поредачил брифинг и настройку FARP: https://github.com/rempopo/CO29_My_Summer_Tanks.ruha/pull/2

- Добавь FV 432 еще 1 штуку, чтобы при респауне можно было их взять (раз танков положил сразу с резервом)
- Добавь пару ЗУ-23-2  или мужиков с 2.5 мужиков с манпадами на в оборону, чтобы нельзя было сильно нагло абьюзить выданные вертолет (ну типа суперфланг делать на левый фланг). Ну или добавь только в саму Ruha, чтобы таки дать возможность как в Варгейм делать хеликоптер инсершены, но чтобы была видимость ААА обороны
